-- +goose Up
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id BIGINT NOT NULL UNIQUE,
    chat_id BIGINT NOT NULL UNIQUE,
    name TEXT,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    parent_id BIGINT REFERENCES areas(id),
    type TEXT NOT NULL,
    name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS source_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    external_key TEXT NOT NULL,
    raw_name TEXT,
    area_id BIGINT REFERENCES areas(id),
    UNIQUE(source, external_key)
);
CREATE TABLE IF NOT EXISTS filters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deal_type TEXT NOT NULL CHECK (deal_type IN ('rent', 'sale')),
    property_types TEXT[] NOT NULL DEFAULT ARRAY['apartment']::TEXT[],
    price_min INTEGER,
    price_max INTEGER,
    rooms_min INTEGER,
    rooms_max INTEGER,
    area_min DOUBLE PRECISION,
    area_max DOUBLE PRECISION,
    activated_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    external_id TEXT NOT NULL,
    url TEXT NOT NULL,
    property_type TEXT NOT NULL DEFAULT 'apartment',
    deal_type TEXT NOT NULL CHECK (deal_type IN ('rent', 'sale')),
    price_eur INTEGER,
    rooms INTEGER,
    area_m2 DOUBLE PRECISION,
    city TEXT,
    district TEXT,
    address TEXT,
    floor INTEGER,
    total_floors INTEGER,
    building_series TEXT,
    building_type TEXT,
    land_area_m2 DOUBLE PRECISION,
    details_enriched BOOLEAN NOT NULL DEFAULT FALSE,
    title TEXT NOT NULL,
    published_at TIMESTAMPTZ,
    image_url TEXT,
    photo_urls JSONB NOT NULL DEFAULT '[]'::JSONB,
    area_id BIGINT REFERENCES areas(id),
    source_area_id BIGINT REFERENCES source_areas(id),
    first_seen_at TIMESTAMPTZ NOT NULL,
    raw_json JSONB,
    UNIQUE(source, external_id)
);
CREATE TABLE IF NOT EXISTS filter_areas (
    filter_id BIGINT NOT NULL REFERENCES filters(id) ON DELETE CASCADE,
    area_id BIGINT NOT NULL REFERENCES areas(id),
    PRIMARY KEY (filter_id, area_id)
);
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filter_id BIGINT NOT NULL REFERENCES filters(id) ON DELETE CASCADE,
    listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    sent_at TIMESTAMPTZ,
    last_error TEXT,
    UNIQUE(filter_id, listing_id)
);
CREATE TABLE IF NOT EXISTS source_state (
    source_key TEXT PRIMARY KEY,
    initialized BOOLEAN NOT NULL DEFAULT FALSE,
    last_success_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS listing_photos (
    listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    position SMALLINT NOT NULL CHECK (position >= 0),
    telegram_file_id TEXT NOT NULL,
    PRIMARY KEY (listing_id, position)
);

-- Safe adoption of databases created by the Python migration chain.
ALTER TABLE filters ADD COLUMN IF NOT EXISTS property_types TEXT[] NOT NULL DEFAULT ARRAY['apartment']::TEXT[];
ALTER TABLE listings ADD COLUMN IF NOT EXISTS property_type TEXT NOT NULL DEFAULT 'apartment';
ALTER TABLE listings ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS floor INTEGER;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS total_floors INTEGER;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS building_series TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS building_type TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS land_area_m2 DOUBLE PRECISION;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS details_enriched BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS photo_urls JSONB NOT NULL DEFAULT '[]'::JSONB;

CREATE INDEX IF NOT EXISTS notifications_due_idx ON notifications(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS filters_enabled_idx ON filters(enabled, deal_type);

-- +goose Down
-- Intentionally irreversible: this baseline may adopt an existing production schema.
