-- +goose Up
CREATE TABLE listing_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    price_eur INTEGER,
    observed_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX listing_price_history_listing_observed_idx
    ON listing_price_history (listing_id, observed_at, id);

INSERT INTO listing_price_history (listing_id, price_eur, observed_at)
SELECT id, price_eur, first_seen_at
FROM listings;

ALTER TABLE notifications
    ADD COLUMN trigger_event_id UUID,
    ADD COLUMN notification_type TEXT NOT NULL DEFAULT 'listing_discovered',
    ADD COLUMN previous_price_eur INTEGER,
    ADD COLUMN current_price_eur INTEGER;

UPDATE notifications
SET trigger_event_id = gen_random_uuid()
WHERE trigger_event_id IS NULL;

ALTER TABLE notifications
    ALTER COLUMN trigger_event_id SET NOT NULL,
    ADD CONSTRAINT notifications_type_check
        CHECK (notification_type IN ('listing_discovered', 'price_decreased'));

ALTER TABLE notifications
    DROP CONSTRAINT IF EXISTS notifications_filter_id_listing_id_key;

ALTER TABLE notifications
    ADD CONSTRAINT notifications_filter_event_key
        UNIQUE (filter_id, trigger_event_id);

-- +goose Down
DELETE FROM notifications
WHERE notification_type = 'price_decreased';

ALTER TABLE notifications
    DROP CONSTRAINT notifications_filter_event_key,
    DROP CONSTRAINT notifications_type_check,
    DROP COLUMN current_price_eur,
    DROP COLUMN previous_price_eur,
    DROP COLUMN notification_type,
    DROP COLUMN trigger_event_id;

ALTER TABLE notifications
    ADD CONSTRAINT notifications_filter_id_listing_id_key
        UNIQUE (filter_id, listing_id);

DROP TABLE listing_price_history;
