-- +goose Up
CREATE TABLE listing_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
    price_eur INTEGER,
    observed_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX listing_price_history_listing_observed_idx
    ON listing_price_history (listing_id, observed_at, id);

ALTER TABLE listings
    ADD COLUMN description TEXT NOT NULL DEFAULT '',
    ADD COLUMN normalized_address TEXT NOT NULL DEFAULT '',
    ADD COLUMN normalized_description TEXT NOT NULL DEFAULT '',
    ADD COLUMN availability_status TEXT NOT NULL DEFAULT 'unknown'
        CHECK (availability_status IN ('active', 'inactive', 'unknown')),
    ADD COLUMN last_seen_at TIMESTAMPTZ,
    ADD COLUMN availability_changed_at TIMESTAMPTZ;

UPDATE listings
SET last_seen_at = first_seen_at,
    availability_changed_at = first_seen_at;

ALTER TABLE listings
    ALTER COLUMN last_seen_at SET NOT NULL,
    ALTER COLUMN availability_changed_at SET NOT NULL;

CREATE TABLE listing_signal_jobs (
    listing_id BIGINT PRIMARY KEY REFERENCES listings(id),
    generation BIGINT NOT NULL DEFAULT 1 CHECK (generation > 0),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'completed')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX listing_signal_jobs_due_idx
    ON listing_signal_jobs (next_attempt_at, listing_id)
    WHERE status = 'pending';

CREATE TABLE listing_signal_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES listings(id),
    generation BIGINT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    outcome TEXT NOT NULL DEFAULT 'processing'
        CHECK (outcome IN ('processing', 'completed', 'failed', 'superseded')),
    error TEXT
);

CREATE INDEX listing_signal_attempts_listing_idx
    ON listing_signal_attempts (listing_id, started_at, id);

CREATE TABLE listing_signal_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES listings(id),
    input_hash TEXT NOT NULL CHECK (length(input_hash) = 64),
    normalization_version TEXT NOT NULL,
    description TEXT NOT NULL,
    normalized_address TEXT NOT NULL,
    normalized_description TEXT NOT NULL,
    structured_facts JSONB NOT NULL,
    photo_urls JSONB NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    UNIQUE (listing_id, input_hash, normalization_version)
);

CREATE INDEX listing_signal_snapshots_listing_idx
    ON listing_signal_snapshots (listing_id, completed_at, id);

CREATE TABLE listing_photo_fingerprints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL REFERENCES listing_signal_snapshots(id),
    listing_id BIGINT NOT NULL REFERENCES listings(id),
    position SMALLINT NOT NULL CHECK (position >= 0),
    source_url TEXT NOT NULL,
    exact_hash TEXT NOT NULL CHECK (length(exact_hash) = 64),
    exact_algorithm TEXT NOT NULL,
    perceptual_hash TEXT NOT NULL CHECK (length(perceptual_hash) = 16),
    perceptual_algorithm TEXT NOT NULL,
    media_type TEXT NOT NULL,
    byte_size INTEGER NOT NULL CHECK (byte_size > 0),
    width INTEGER NOT NULL CHECK (width > 0),
    height INTEGER NOT NULL CHECK (height > 0),
    created_at TIMESTAMPTZ NOT NULL,
    UNIQUE (snapshot_id, position)
);

CREATE INDEX listing_photo_fingerprints_exact_idx
    ON listing_photo_fingerprints (exact_algorithm, exact_hash);

CREATE INDEX listing_photo_fingerprints_perceptual_idx
    ON listing_photo_fingerprints (perceptual_algorithm, perceptual_hash);

CREATE INDEX listing_photo_fingerprints_listing_url_idx
    ON listing_photo_fingerprints (listing_id, source_url, created_at DESC, id DESC);

CREATE TABLE properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    merged_into_property_id BIGINT REFERENCES properties(id),
    merged_at TIMESTAMPTZ,
    CHECK ((merged_into_property_id IS NULL) = (merged_at IS NULL)),
    CHECK (merged_into_property_id IS NULL OR merged_into_property_id <> id)
);

CREATE TABLE duplicate_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    left_listing_id BIGINT NOT NULL REFERENCES listings(id),
    right_listing_id BIGINT NOT NULL REFERENCES listings(id),
    left_snapshot_id BIGINT NOT NULL REFERENCES listing_signal_snapshots(id),
    right_snapshot_id BIGINT NOT NULL REFERENCES listing_signal_snapshots(id),
    rule_version TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    automatic_status TEXT NOT NULL CHECK (automatic_status IN ('accepted', 'ambiguous', 'rejected')),
    status TEXT NOT NULL CHECK (status IN ('accepted', 'ambiguous', 'rejected')),
    evidence JSONB NOT NULL,
    evaluated_at TIMESTAMPTZ NOT NULL,
    overridden_at TIMESTAMPTZ,
    override_reason TEXT,
    CHECK (left_listing_id < right_listing_id),
    CHECK (left_snapshot_id <> right_snapshot_id),
    UNIQUE (left_snapshot_id, right_snapshot_id, rule_version)
);

CREATE INDEX duplicate_decisions_pair_idx
    ON duplicate_decisions (left_listing_id, right_listing_id, evaluated_at, id);

CREATE INDEX duplicate_decisions_status_score_idx
    ON duplicate_decisions (status, confidence DESC, evaluated_at DESC);

CREATE TABLE property_listing_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL REFERENCES properties(id),
    listing_id BIGINT NOT NULL REFERENCES listings(id),
    decision_id BIGINT REFERENCES duplicate_decisions(id),
    valid_from TIMESTAMPTZ NOT NULL,
    valid_to TIMESTAMPTZ,
    reason TEXT NOT NULL,
    CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE UNIQUE INDEX property_listing_memberships_current_listing_idx
    ON property_listing_memberships (listing_id)
    WHERE valid_to IS NULL;

CREATE INDEX property_listing_memberships_current_property_idx
    ON property_listing_memberships (property_id, listing_id)
    WHERE valid_to IS NULL;

CREATE TABLE duplicate_resolution_jobs (
    snapshot_id BIGINT PRIMARY KEY REFERENCES listing_signal_snapshots(id),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'completed')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX duplicate_resolution_jobs_due_idx
    ON duplicate_resolution_jobs (next_attempt_at, snapshot_id)
    WHERE status = 'pending';

CREATE TABLE duplicate_resolution_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL REFERENCES listing_signal_snapshots(id),
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    outcome TEXT NOT NULL DEFAULT 'processing'
        CHECK (outcome IN ('processing', 'completed', 'failed')),
    candidate_count INTEGER,
    accepted_count INTEGER,
    error TEXT
);

CREATE INDEX duplicate_resolution_attempts_snapshot_idx
    ON duplicate_resolution_attempts (snapshot_id, started_at, id);

CREATE VIEW duplicate_decision_inspection AS
SELECT d.id,
       d.rule_version,
       d.confidence,
       d.automatic_status,
       d.status,
       d.evidence,
       d.evaluated_at,
       d.overridden_at,
       d.override_reason,
       left_listing.source AS left_source,
       left_listing.external_id AS left_external_id,
       right_listing.source AS right_source,
       right_listing.external_id AS right_external_id,
       left_membership.property_id AS left_property_id,
       right_membership.property_id AS right_property_id
FROM duplicate_decisions d
JOIN listings left_listing ON left_listing.id = d.left_listing_id
JOIN listings right_listing ON right_listing.id = d.right_listing_id
LEFT JOIN property_listing_memberships left_membership
       ON left_membership.listing_id = d.left_listing_id AND left_membership.valid_to IS NULL
LEFT JOIN property_listing_memberships right_membership
       ON right_membership.listing_id = d.right_listing_id AND right_membership.valid_to IS NULL;

CREATE VIEW duplicate_score_distribution AS
SELECT rule_version,
       status,
       least(20, width_bucket(confidence, 0::DOUBLE PRECISION, 1::DOUBLE PRECISION, 20)) AS score_bucket,
       count(*) AS decision_count
FROM duplicate_decisions
GROUP BY rule_version, status, score_bucket;

CREATE TABLE listing_availability_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES listings(id),
    status TEXT NOT NULL CHECK (status IN ('active', 'inactive', 'unknown')),
    previous_status TEXT CHECK (previous_status IN ('active', 'inactive', 'unknown')),
    observed_at TIMESTAMPTZ NOT NULL,
    observation_kind TEXT NOT NULL CHECK (observation_kind IN ('migration', 'feed', 'provider_check')),
    evidence TEXT NOT NULL,
    is_transition BOOLEAN NOT NULL,
    CHECK (is_transition = (previous_status IS NOT NULL AND previous_status <> status))
);

CREATE INDEX listing_availability_observations_listing_idx
    ON listing_availability_observations (listing_id, observed_at, id);

CREATE INDEX listing_availability_observations_status_idx
    ON listing_availability_observations (status, observed_at DESC);

CREATE TABLE listing_availability_jobs (
    listing_id BIGINT PRIMARY KEY REFERENCES listings(id),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_at TIMESTAMPTZ,
    last_error TEXT,
    priority_requested BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX listing_availability_jobs_due_idx
    ON listing_availability_jobs (next_attempt_at, listing_id)
    WHERE status = 'pending';

CREATE INDEX listing_availability_jobs_priority_idx
    ON listing_availability_jobs (next_attempt_at, listing_id)
    WHERE status = 'pending' AND priority_requested;

CREATE TABLE listing_availability_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES listings(id),
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    outcome TEXT NOT NULL DEFAULT 'processing'
        CHECK (outcome IN ('processing', 'active', 'inactive', 'unknown', 'failed')),
    evidence TEXT,
    error TEXT
);

CREATE INDEX listing_availability_attempts_listing_idx
    ON listing_availability_attempts (listing_id, started_at, id);

CREATE VIEW current_active_listing_offers AS
SELECT l.*
FROM listings l
WHERE l.availability_status = 'active';

ALTER TABLE notifications
    ADD COLUMN trigger_event_id UUID,
    ADD COLUMN notification_type TEXT NOT NULL DEFAULT 'listing_discovered',
    ADD COLUMN previous_price_eur INTEGER,
    ADD COLUMN current_price_eur INTEGER,
    ADD COLUMN property_id BIGINT REFERENCES properties(id),
    ADD COLUMN comparison_listing_id BIGINT REFERENCES listings(id),
    ADD COLUMN listing_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN active_alternatives JSONB NOT NULL DEFAULT '[]'::JSONB;

UPDATE notifications
SET trigger_event_id = gen_random_uuid()
WHERE trigger_event_id IS NULL;

ALTER TABLE notifications
    ALTER COLUMN trigger_event_id SET NOT NULL,
    ADD CONSTRAINT notifications_type_check
        CHECK (notification_type IN ('listing_discovered', 'price_changed', 'relisting_price_changed', 'cheaper_offer'));

ALTER TABLE notifications
    DROP CONSTRAINT IF EXISTS notifications_filter_id_listing_id_key,
    ADD CONSTRAINT notifications_filter_event_key
        UNIQUE (filter_id, trigger_event_id);

CREATE UNIQUE INDEX notifications_filter_property_discovery_idx
    ON notifications (filter_id, property_id)
    WHERE notification_type = 'listing_discovered' AND property_id IS NOT NULL;

CREATE INDEX notifications_filter_property_idx
    ON notifications (filter_id, property_id, id)
    WHERE property_id IS NOT NULL;

INSERT INTO listing_price_history (listing_id, price_eur, observed_at)
SELECT id, price_eur, first_seen_at
FROM listings;

INSERT INTO listing_signal_jobs (listing_id)
SELECT id
FROM listings
ON CONFLICT (listing_id) DO NOTHING;

INSERT INTO listing_availability_observations
    (listing_id, status, previous_status, observed_at, observation_kind, evidence, is_transition)
SELECT id, 'unknown', NULL, first_seen_at, 'migration', 'pre-tracking listing', FALSE
FROM listings;

INSERT INTO listing_availability_jobs (listing_id)
SELECT id
FROM listings
ON CONFLICT (listing_id) DO NOTHING;

-- +goose Down
DROP INDEX notifications_filter_property_idx;
DROP INDEX notifications_filter_property_discovery_idx;

DELETE FROM notifications
WHERE notification_type <> 'listing_discovered';

WITH ranked AS (
    SELECT id,
           row_number() OVER (PARTITION BY filter_id, listing_id ORDER BY id) AS position
    FROM notifications
)
DELETE FROM notifications n
USING ranked
WHERE n.id = ranked.id
  AND ranked.position > 1;

ALTER TABLE notifications
    DROP CONSTRAINT notifications_filter_event_key,
    DROP CONSTRAINT notifications_type_check,
    DROP COLUMN active_alternatives,
    DROP COLUMN listing_snapshot,
    DROP COLUMN comparison_listing_id,
    DROP COLUMN property_id,
    DROP COLUMN current_price_eur,
    DROP COLUMN previous_price_eur,
    DROP COLUMN notification_type,
    DROP COLUMN trigger_event_id,
    ADD CONSTRAINT notifications_filter_id_listing_id_key
        UNIQUE (filter_id, listing_id);

DROP VIEW current_active_listing_offers;
DROP TABLE listing_availability_attempts;
DROP TABLE listing_availability_jobs;
DROP TABLE listing_availability_observations;

DROP VIEW duplicate_score_distribution;
DROP VIEW duplicate_decision_inspection;
DROP TABLE duplicate_resolution_attempts;
DROP TABLE duplicate_resolution_jobs;
DROP TABLE property_listing_memberships;
DROP TABLE duplicate_decisions;
DROP TABLE properties;

DROP TABLE listing_photo_fingerprints;
DROP TABLE listing_signal_snapshots;
DROP TABLE listing_signal_attempts;
DROP TABLE listing_signal_jobs;

ALTER TABLE listings
    DROP COLUMN availability_changed_at,
    DROP COLUMN last_seen_at,
    DROP COLUMN availability_status,
    DROP COLUMN normalized_description,
    DROP COLUMN normalized_address,
    DROP COLUMN description;

DROP TABLE listing_price_history;
