// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deduplication.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findDuplicateCandidateSnapshotIDs = `-- name: FindDuplicateCandidateSnapshotIDs :many
WITH latest_snapshots AS (
    SELECT DISTINCT ON (snapshot.listing_id)
        snapshot.id,
        snapshot.listing_id,
        snapshot.normalized_address,
        snapshot.structured_facts,
        snapshot.completed_at
    FROM listing_signal_snapshots AS snapshot
    WHERE snapshot.listing_id <> $10
    ORDER BY
        snapshot.listing_id,
        snapshot.completed_at DESC,
        snapshot.id DESC
)
SELECT id
FROM latest_snapshots
WHERE structured_facts->>'property_type' = $1::text
  AND structured_facts->>'deal_type' = $2::text
  AND (
      (
          $3::text <> ''
          AND structured_facts->>'area_key' = $3
      )
      OR (
          $4::text <> ''
          AND normalized_address = $4
      )
  )
  AND (
      $5::integer IS NULL
      OR structured_facts->>'rooms' IS NULL
      OR (structured_facts->>'rooms')::integer = $5
  )
  AND (
      $6::double precision IS NULL
      OR structured_facts->>'area_m2' IS NULL
      OR abs(
          (structured_facts->>'area_m2')::double precision
          - $6
      ) <= greatest(5.0, $6 * 0.08)
  )
  AND (
      $7::integer IS NULL
      OR structured_facts->>'floor' IS NULL
      OR (structured_facts->>'floor')::integer = $7
  )
  AND (
      $8::double precision IS NULL
      OR structured_facts->>'land_area_m2' IS NULL
      OR abs(
          (structured_facts->>'land_area_m2')::double precision
          - $8
      ) <= greatest(50.0, $8 * 0.10)
  )
ORDER BY
    (
        normalized_address = $4
        AND $4::text <> ''
    ) DESC,
    completed_at DESC,
    id DESC
LIMIT $9
`

type FindDuplicateCandidateSnapshotIDsParams struct {
	PropertyType      string   `json:"property_type"`
	DealType          string   `json:"deal_type"`
	AreaKey           string   `json:"area_key"`
	NormalizedAddress string   `json:"normalized_address"`
	Rooms             *int     `json:"rooms"`
	AreaM2            *float64 `json:"area_m2"`
	Floor             *int     `json:"floor"`
	LandAreaM2        *float64 `json:"land_area_m2"`
	CandidateLimit    int32    `json:"candidate_limit"`
	ListingID         int64    `json:"listing_id"`
}

func (q *Queries) FindDuplicateCandidateSnapshotIDs(ctx context.Context, arg FindDuplicateCandidateSnapshotIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, findDuplicateCandidateSnapshotIDs,
		arg.PropertyType,
		arg.DealType,
		arg.AreaKey,
		arg.NormalizedAddress,
		arg.Rooms,
		arg.AreaM2,
		arg.Floor,
		arg.LandAreaM2,
		arg.CandidateLimit,
		arg.ListingID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDuplicateDecision = `-- name: InsertDuplicateDecision :one
INSERT INTO duplicate_decisions (
    left_listing_id,
    right_listing_id,
    left_snapshot_id,
    right_snapshot_id,
    rule_version,
    confidence,
    automatic_status,
    status,
    evidence,
    evaluated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $7,
    $8,
    $9
)
ON CONFLICT (left_snapshot_id, right_snapshot_id, rule_version) DO UPDATE
SET confidence = duplicate_decisions.confidence
RETURNING id, status
`

type InsertDuplicateDecisionParams struct {
	LeftListingID   int64              `json:"left_listing_id"`
	RightListingID  int64              `json:"right_listing_id"`
	LeftSnapshotID  int64              `json:"left_snapshot_id"`
	RightSnapshotID int64              `json:"right_snapshot_id"`
	RuleVersion     string             `json:"rule_version"`
	Confidence      float64            `json:"confidence"`
	DecisionStatus  string             `json:"decision_status"`
	Evidence        []byte             `json:"evidence"`
	EvaluatedAt     pgtype.Timestamptz `json:"evaluated_at"`
}

type InsertDuplicateDecisionRow struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) InsertDuplicateDecision(ctx context.Context, arg InsertDuplicateDecisionParams) (InsertDuplicateDecisionRow, error) {
	row := q.db.QueryRow(ctx, insertDuplicateDecision,
		arg.LeftListingID,
		arg.RightListingID,
		arg.LeftSnapshotID,
		arg.RightSnapshotID,
		arg.RuleVersion,
		arg.Confidence,
		arg.DecisionStatus,
		arg.Evidence,
		arg.EvaluatedAt,
	)
	var i InsertDuplicateDecisionRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const listOtherPropertyOffers = `-- name: ListOtherPropertyOffers :many
SELECT
    listing.id,
    listing.source,
    listing.url,
    event_price.price_eur AS event_price_eur,
    last_known_price.price_eur AS last_known_price_eur,
    listing.availability_status,
    listing.first_seen_at
FROM property_listing_memberships AS membership
JOIN listings AS listing
  ON listing.id = membership.listing_id
LEFT JOIN LATERAL (
    SELECT history.price_eur
    FROM listing_price_history AS history
    WHERE history.listing_id = listing.id
      AND history.observed_at <= $1
    ORDER BY history.observed_at DESC, history.id DESC
    LIMIT 1
) AS event_price ON TRUE
LEFT JOIN LATERAL (
    SELECT history.price_eur
    FROM listing_price_history AS history
    WHERE history.listing_id = listing.id
      AND history.observed_at <= $1
      AND history.price_eur IS NOT NULL
    ORDER BY history.observed_at DESC, history.id DESC
    LIMIT 1
) AS last_known_price ON TRUE
WHERE membership.property_id = $2
  AND membership.valid_to IS NULL
  AND listing.id <> $3
ORDER BY listing.first_seen_at DESC, listing.id DESC
`

type ListOtherPropertyOffersParams struct {
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	PropertyID        int64              `json:"property_id"`
	ExcludedListingID int64              `json:"excluded_listing_id"`
}

type ListOtherPropertyOffersRow struct {
	ID                 int64              `json:"id"`
	Source             string             `json:"source"`
	URL                string             `json:"url"`
	EventPriceEUR      *int               `json:"event_price_eur"`
	LastKnownPriceEUR  *int               `json:"last_known_price_eur"`
	AvailabilityStatus string             `json:"availability_status"`
	FirstSeenAt        pgtype.Timestamptz `json:"first_seen_at"`
}

func (q *Queries) ListOtherPropertyOffers(ctx context.Context, arg ListOtherPropertyOffersParams) ([]ListOtherPropertyOffersRow, error) {
	rows, err := q.db.Query(ctx, listOtherPropertyOffers, arg.OccurredAt, arg.PropertyID, arg.ExcludedListingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOtherPropertyOffersRow{}
	for rows.Next() {
		var i ListOtherPropertyOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.URL,
			&i.EventPriceEUR,
			&i.LastKnownPriceEUR,
			&i.AvailabilityStatus,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotPhotoFingerprints = `-- name: ListSnapshotPhotoFingerprints :many
SELECT
    position,
    source_url,
    exact_hash,
    exact_algorithm,
    perceptual_hash,
    perceptual_algorithm,
    media_type,
    byte_size,
    width,
    height
FROM listing_photo_fingerprints
WHERE snapshot_id = $1
ORDER BY position
`

type ListSnapshotPhotoFingerprintsRow struct {
	Position            int16  `json:"position"`
	SourceURL           string `json:"source_url"`
	ExactHash           string `json:"exact_hash"`
	ExactAlgorithm      string `json:"exact_algorithm"`
	PerceptualHash      string `json:"perceptual_hash"`
	PerceptualAlgorithm string `json:"perceptual_algorithm"`
	MediaType           string `json:"media_type"`
	ByteSize            int    `json:"byte_size"`
	Width               int    `json:"width"`
	Height              int    `json:"height"`
}

func (q *Queries) ListSnapshotPhotoFingerprints(ctx context.Context, snapshotID int64) ([]ListSnapshotPhotoFingerprintsRow, error) {
	rows, err := q.db.Query(ctx, listSnapshotPhotoFingerprints, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnapshotPhotoFingerprintsRow{}
	for rows.Next() {
		var i ListSnapshotPhotoFingerprintsRow
		if err := rows.Scan(
			&i.Position,
			&i.SourceURL,
			&i.ExactHash,
			&i.ExactAlgorithm,
			&i.PerceptualHash,
			&i.PerceptualAlgorithm,
			&i.MediaType,
			&i.ByteSize,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadListingEvidence = `-- name: LoadListingEvidence :one
SELECT
    snapshot.id AS snapshot_id,
    snapshot.completed_at,
    snapshot.description,
    snapshot.normalized_address,
    snapshot.normalized_description,
    snapshot.structured_facts,
    listing.id AS listing_id,
    listing.source,
    listing.external_id,
    listing.url
FROM listing_signal_snapshots AS snapshot
JOIN listings AS listing
  ON listing.id = snapshot.listing_id
WHERE snapshot.id = $1
`

type LoadListingEvidenceRow struct {
	SnapshotID            int64              `json:"snapshot_id"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	Description           string             `json:"description"`
	NormalizedAddress     string             `json:"normalized_address"`
	NormalizedDescription string             `json:"normalized_description"`
	StructuredFacts       []byte             `json:"structured_facts"`
	ListingID             int64              `json:"listing_id"`
	Source                string             `json:"source"`
	ExternalID            string             `json:"external_id"`
	URL                   string             `json:"url"`
}

func (q *Queries) LoadListingEvidence(ctx context.Context, snapshotID int64) (LoadListingEvidenceRow, error) {
	row := q.db.QueryRow(ctx, loadListingEvidence, snapshotID)
	var i LoadListingEvidenceRow
	err := row.Scan(
		&i.SnapshotID,
		&i.CompletedAt,
		&i.Description,
		&i.NormalizedAddress,
		&i.NormalizedDescription,
		&i.StructuredFacts,
		&i.ListingID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
	)
	return i, err
}

const prioritizePropertyAvailabilityChecks = `-- name: PrioritizePropertyAvailabilityChecks :exec
UPDATE listing_availability_jobs
SET next_attempt_at = '1970-01-01 00:00:00+00',
    priority_requested = TRUE,
    updated_at = $1
WHERE listing_availability_jobs.status = 'pending'
  AND listing_availability_jobs.listing_id <> $2
  AND listing_availability_jobs.listing_id IN (
      SELECT membership.listing_id
      FROM property_listing_memberships AS membership
      JOIN listings AS listing
        ON listing.id = membership.listing_id
      WHERE membership.property_id = $3
        AND membership.valid_to IS NULL
        AND listing.availability_status <> 'inactive'
  )
`

type PrioritizePropertyAvailabilityChecksParams struct {
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExcludedListingID int64              `json:"excluded_listing_id"`
	PropertyID        int64              `json:"property_id"`
}

func (q *Queries) PrioritizePropertyAvailabilityChecks(ctx context.Context, arg PrioritizePropertyAvailabilityChecksParams) error {
	_, err := q.db.Exec(ctx, prioritizePropertyAvailabilityChecks, arg.UpdatedAt, arg.ExcludedListingID, arg.PropertyID)
	return err
}

const resolvedPropertyIDForListing = `-- name: ResolvedPropertyIDForListing :one
SELECT membership.property_id
FROM property_listing_memberships AS membership
WHERE membership.listing_id = $1
  AND membership.valid_to IS NULL
  AND EXISTS (
      SELECT 1
      FROM listing_signal_snapshots AS snapshot
      JOIN duplicate_resolution_jobs AS resolution_job
        ON resolution_job.snapshot_id = snapshot.id
       AND resolution_job.status = 'completed'
      WHERE snapshot.listing_id = $1
  )
`

func (q *Queries) ResolvedPropertyIDForListing(ctx context.Context, listingID int64) (int64, error) {
	row := q.db.QueryRow(ctx, resolvedPropertyIDForListing, listingID)
	var property_id int64
	err := row.Scan(&property_id)
	return property_id, err
}

const scheduleMissingPropertyAvailabilityChecks = `-- name: ScheduleMissingPropertyAvailabilityChecks :one
WITH missing_listings AS MATERIALIZED (
    SELECT membership.listing_id
    FROM property_listing_memberships AS membership
    JOIN listings AS listing
      ON listing.id = membership.listing_id
    WHERE membership.property_id = $1
      AND membership.valid_to IS NULL
      AND membership.listing_id <> $2
      AND listing.availability_status <> 'inactive'
      AND NOT EXISTS (
          SELECT 1
          FROM listing_availability_observations AS observation
          WHERE observation.listing_id = membership.listing_id
            AND observation.observation_kind = 'provider_check'
            AND observation.observed_at >= $3
      )
),
scheduled AS (
    INSERT INTO listing_availability_jobs (
        listing_id,
        next_attempt_at,
        priority_requested,
        created_at,
        updated_at
    )
    SELECT
        listing_id,
        now(),
        TRUE,
        now(),
        now()
    FROM missing_listings
    ON CONFLICT (listing_id) DO UPDATE
    SET next_attempt_at = CASE
            WHEN listing_availability_jobs.status = 'pending'
                THEN least(listing_availability_jobs.next_attempt_at, excluded.next_attempt_at)
            ELSE listing_availability_jobs.next_attempt_at
        END,
        priority_requested = CASE
            WHEN listing_availability_jobs.status = 'pending' THEN TRUE
            ELSE listing_availability_jobs.priority_requested
        END,
        updated_at = CASE
            WHEN listing_availability_jobs.status = 'pending' THEN excluded.updated_at
            ELSE listing_availability_jobs.updated_at
        END
    RETURNING listing_id
)
SELECT count(*)
FROM missing_listings
`

type ScheduleMissingPropertyAvailabilityChecksParams struct {
	PropertyID        int64              `json:"property_id"`
	ExcludedListingID int64              `json:"excluded_listing_id"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) ScheduleMissingPropertyAvailabilityChecks(ctx context.Context, arg ScheduleMissingPropertyAvailabilityChecksParams) (int64, error) {
	row := q.db.QueryRow(ctx, scheduleMissingPropertyAvailabilityChecks, arg.PropertyID, arg.ExcludedListingID, arg.ObservedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userWasNotifiedAboutProperty = `-- name: UserWasNotifiedAboutProperty :one
SELECT EXISTS (
    SELECT 1
    FROM notifications AS notification
    JOIN filters AS filter
      ON filter.id = notification.filter_id
    JOIN property_listing_memberships AS membership
      ON membership.listing_id = notification.listing_id
     AND membership.valid_to IS NULL
    WHERE filter.user_id = $1
      AND membership.property_id = $2
)
`

type UserWasNotifiedAboutPropertyParams struct {
	UserID     int64 `json:"user_id"`
	PropertyID int64 `json:"property_id"`
}

func (q *Queries) UserWasNotifiedAboutProperty(ctx context.Context, arg UserWasNotifiedAboutPropertyParams) (bool, error) {
	row := q.db.QueryRow(ctx, userWasNotifiedAboutProperty, arg.UserID, arg.PropertyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
