// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: filters.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEnabledFilters = `-- name: ListEnabledFilters :many
SELECT
    filter.id,
    filter.user_id,
    filter.deal_type,
    filter.property_types,
    filter.price_min,
    filter.price_max,
    filter.rooms_min,
    filter.rooms_max,
    filter.area_min,
    filter.area_max,
    filter.activated_at,
    coalesce(
        array_agg(area.key ORDER BY area.key)
            FILTER (WHERE area.id IS NOT NULL),
        '{}'
    )::text[] AS area_keys
FROM filters AS filter
LEFT JOIN filter_areas AS filter_area
  ON filter_area.filter_id = filter.id
LEFT JOIN areas AS area
  ON area.id = filter_area.area_id
WHERE filter.enabled = TRUE
GROUP BY filter.id
`

type ListEnabledFiltersRow struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	DealType      string             `json:"deal_type"`
	PropertyTypes []string           `json:"property_types"`
	PriceMin      *int               `json:"price_min"`
	PriceMax      *int               `json:"price_max"`
	RoomsMin      *int               `json:"rooms_min"`
	RoomsMax      *int               `json:"rooms_max"`
	AreaMin       *float64           `json:"area_min"`
	AreaMax       *float64           `json:"area_max"`
	ActivatedAt   pgtype.Timestamptz `json:"activated_at"`
	AreaKeys      []string           `json:"area_keys"`
}

func (q *Queries) ListEnabledFilters(ctx context.Context) ([]ListEnabledFiltersRow, error) {
	rows, err := q.db.Query(ctx, listEnabledFilters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledFiltersRow{}
	for rows.Next() {
		var i ListEnabledFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DealType,
			&i.PropertyTypes,
			&i.PriceMin,
			&i.PriceMax,
			&i.RoomsMin,
			&i.RoomsMax,
			&i.AreaMin,
			&i.AreaMax,
			&i.ActivatedAt,
			&i.AreaKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFilters = `-- name: ListSavedFilters :many
SELECT
    filter.id,
    filter.deal_type,
    filter.property_types,
    filter.price_min,
    filter.price_max,
    filter.rooms_min,
    filter.rooms_max,
    filter.area_min,
    filter.area_max,
    filter.enabled,
    coalesce(
        array_agg(
            CASE
                WHEN parent_area.name IS NULL THEN area.name
                ELSE area.name || ' (' || parent_area.name || ')'
            END
            ORDER BY area.key
        ) FILTER (WHERE area.id IS NOT NULL),
        '{}'
    )::text[] AS area_labels
FROM filters AS filter
JOIN users AS app_user
  ON app_user.id = filter.user_id
LEFT JOIN filter_areas AS filter_area
  ON filter_area.filter_id = filter.id
LEFT JOIN areas AS area
  ON area.id = filter_area.area_id
LEFT JOIN areas AS parent_area
  ON parent_area.id = area.parent_id
WHERE app_user.telegram_user_id = $1
GROUP BY filter.id
ORDER BY filter.id
`

type ListSavedFiltersRow struct {
	ID            int64    `json:"id"`
	DealType      string   `json:"deal_type"`
	PropertyTypes []string `json:"property_types"`
	PriceMin      *int     `json:"price_min"`
	PriceMax      *int     `json:"price_max"`
	RoomsMin      *int     `json:"rooms_min"`
	RoomsMax      *int     `json:"rooms_max"`
	AreaMin       *float64 `json:"area_min"`
	AreaMax       *float64 `json:"area_max"`
	Enabled       bool     `json:"enabled"`
	AreaLabels    []string `json:"area_labels"`
}

func (q *Queries) ListSavedFilters(ctx context.Context, telegramUserID int64) ([]ListSavedFiltersRow, error) {
	rows, err := q.db.Query(ctx, listSavedFilters, telegramUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedFiltersRow{}
	for rows.Next() {
		var i ListSavedFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.DealType,
			&i.PropertyTypes,
			&i.PriceMin,
			&i.PriceMax,
			&i.RoomsMin,
			&i.RoomsMax,
			&i.AreaMin,
			&i.AreaMax,
			&i.Enabled,
			&i.AreaLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
