// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimableAvailabilityListingIDs = `-- name: ClaimableAvailabilityListingIDs :many
SELECT job.listing_id
FROM listing_availability_jobs AS job
JOIN listings AS listing
  ON listing.id = job.listing_id
WHERE job.status = 'pending'
  AND job.next_attempt_at <= now()
  AND listing.availability_status <> 'inactive'
  AND (
      job.priority_requested
      OR listing.availability_status = 'unknown'
      OR listing.last_seen_at <= now() - ($1::integer * interval '1 second')
  )
ORDER BY
    job.priority_requested DESC,
    job.next_attempt_at,
    job.listing_id
FOR UPDATE OF job SKIP LOCKED
LIMIT $2
`

type ClaimableAvailabilityListingIDsParams struct {
	StaleSeconds int   `json:"stale_seconds"`
	JobLimit     int32 `json:"job_limit"`
}

func (q *Queries) ClaimableAvailabilityListingIDs(ctx context.Context, arg ClaimableAvailabilityListingIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, claimableAvailabilityListingIDs, arg.StaleSeconds, arg.JobLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var listing_id int64
		if err := rows.Scan(&listing_id); err != nil {
			return nil, err
		}
		items = append(items, listing_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimableDuplicateResolutionSnapshotIDs = `-- name: ClaimableDuplicateResolutionSnapshotIDs :many
SELECT snapshot_id
FROM duplicate_resolution_jobs
WHERE (
        status = 'pending'
        AND next_attempt_at <= now()
    )
   OR (
        status = 'processing'
        AND claimed_at < now() - ($1::integer * interval '1 second')
    )
ORDER BY next_attempt_at, snapshot_id
FOR UPDATE SKIP LOCKED
LIMIT $2
`

type ClaimableDuplicateResolutionSnapshotIDsParams struct {
	StaleSeconds int   `json:"stale_seconds"`
	JobLimit     int32 `json:"job_limit"`
}

func (q *Queries) ClaimableDuplicateResolutionSnapshotIDs(ctx context.Context, arg ClaimableDuplicateResolutionSnapshotIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, claimableDuplicateResolutionSnapshotIDs, arg.StaleSeconds, arg.JobLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var snapshot_id int64
		if err := rows.Scan(&snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, snapshot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimableListingSignalJobs = `-- name: ClaimableListingSignalJobs :many
SELECT listing_id, generation
FROM listing_signal_jobs
WHERE (
        status = 'pending'
        AND next_attempt_at <= now()
    )
   OR (
        status = 'processing'
        AND claimed_at < now() - ($1::integer * interval '1 second')
    )
ORDER BY next_attempt_at, listing_id
FOR UPDATE SKIP LOCKED
LIMIT $2
`

type ClaimableListingSignalJobsParams struct {
	StaleSeconds int   `json:"stale_seconds"`
	JobLimit     int32 `json:"job_limit"`
}

type ClaimableListingSignalJobsRow struct {
	ListingID  int64 `json:"listing_id"`
	Generation int64 `json:"generation"`
}

func (q *Queries) ClaimableListingSignalJobs(ctx context.Context, arg ClaimableListingSignalJobsParams) ([]ClaimableListingSignalJobsRow, error) {
	rows, err := q.db.Query(ctx, claimableListingSignalJobs, arg.StaleSeconds, arg.JobLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimableListingSignalJobsRow{}
	for rows.Next() {
		var i ClaimableListingSignalJobsRow
		if err := rows.Scan(&i.ListingID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireStaleAvailabilityAttempts = `-- name: ExpireStaleAvailabilityAttempts :exec
UPDATE listing_availability_attempts AS attempt
SET finished_at = $1,
    outcome = 'failed',
    error = 'worker claim expired'
FROM listing_availability_jobs AS job
WHERE attempt.listing_id = job.listing_id
  AND attempt.outcome = 'processing'
  AND job.status = 'processing'
  AND job.claimed_at < $1::timestamptz
      - ($2::integer * interval '1 second')
`

type ExpireStaleAvailabilityAttemptsParams struct {
	ExpiredAt    pgtype.Timestamptz `json:"expired_at"`
	StaleSeconds int                `json:"stale_seconds"`
}

func (q *Queries) ExpireStaleAvailabilityAttempts(ctx context.Context, arg ExpireStaleAvailabilityAttemptsParams) error {
	_, err := q.db.Exec(ctx, expireStaleAvailabilityAttempts, arg.ExpiredAt, arg.StaleSeconds)
	return err
}

const releaseStaleAvailabilityJobs = `-- name: ReleaseStaleAvailabilityJobs :exec
UPDATE listing_availability_jobs
SET status = 'pending',
    claimed_at = NULL,
    updated_at = $1
WHERE status = 'processing'
  AND claimed_at < $1::timestamptz
      - ($2::integer * interval '1 second')
`

type ReleaseStaleAvailabilityJobsParams struct {
	ReleasedAt   pgtype.Timestamptz `json:"released_at"`
	StaleSeconds int                `json:"stale_seconds"`
}

func (q *Queries) ReleaseStaleAvailabilityJobs(ctx context.Context, arg ReleaseStaleAvailabilityJobsParams) error {
	_, err := q.db.Exec(ctx, releaseStaleAvailabilityJobs, arg.ReleasedAt, arg.StaleSeconds)
	return err
}
