// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertListing = `-- name: InsertListing :one
INSERT INTO listings (
    source,
    external_id,
    url,
    property_type,
    deal_type,
    price_eur,
    rooms,
    area_m2,
    city,
    district,
    address,
    floor,
    total_floors,
    building_series,
    building_type,
    land_area_m2,
    details_enriched,
    title,
    description,
    published_at,
    image_url,
    photo_urls,
    area_id,
    source_area_id,
    first_seen_at,
    availability_status,
    last_seen_at,
    availability_changed_at,
    raw_json
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    nullif($9::text, ''),
    nullif($10::text, ''),
    nullif($11::text, ''),
    $12,
    $13,
    nullif($14::text, ''),
    nullif($15::text, ''),
    $16,
    $17,
    $18,
    $19,
    $20,
    nullif($21::text, ''),
    $22,
    $23,
    $24,
    $25,
    'active',
    $25,
    $25,
    $26
)
ON CONFLICT (source, external_id) DO NOTHING
RETURNING id
`

type InsertListingParams struct {
	Source          string             `json:"source"`
	ExternalID      string             `json:"external_id"`
	URL             string             `json:"url"`
	PropertyType    string             `json:"property_type"`
	DealType        string             `json:"deal_type"`
	PriceEUR        *int               `json:"price_eur"`
	Rooms           *int               `json:"rooms"`
	AreaM2          *float64           `json:"area_m2"`
	City            string             `json:"city"`
	District        string             `json:"district"`
	Address         string             `json:"address"`
	Floor           *int               `json:"floor"`
	TotalFloors     *int               `json:"total_floors"`
	BuildingSeries  string             `json:"building_series"`
	BuildingType    string             `json:"building_type"`
	LandAreaM2      *float64           `json:"land_area_m2"`
	DetailsEnriched bool               `json:"details_enriched"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ImageURL        string             `json:"image_url"`
	PhotoURLs       []byte             `json:"photo_urls"`
	AreaID          *int64             `json:"area_id"`
	SourceAreaID    *int64             `json:"source_area_id"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
	RawJSON         []byte             `json:"raw_json"`
}

func (q *Queries) InsertListing(ctx context.Context, arg InsertListingParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertListing,
		arg.Source,
		arg.ExternalID,
		arg.URL,
		arg.PropertyType,
		arg.DealType,
		arg.PriceEUR,
		arg.Rooms,
		arg.AreaM2,
		arg.City,
		arg.District,
		arg.Address,
		arg.Floor,
		arg.TotalFloors,
		arg.BuildingSeries,
		arg.BuildingType,
		arg.LandAreaM2,
		arg.DetailsEnriched,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.ImageURL,
		arg.PhotoURLs,
		arg.AreaID,
		arg.SourceAreaID,
		arg.FirstSeenAt,
		arg.RawJSON,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listStoredListingsForEnrichment = `-- name: ListStoredListingsForEnrichment :many
SELECT
    listing.external_id,
    listing.price_eur,
    coalesce(listing.description, '') AS description,
    coalesce(listing.address, '') AS address,
    listing.rooms,
    listing.area_m2,
    listing.floor,
    listing.total_floors,
    coalesce(listing.building_series, '') AS building_series,
    coalesce(listing.building_type, '') AS building_type,
    listing.land_area_m2,
    coalesce(listing.image_url, '') AS image_url,
    listing.photo_urls,
    coalesce(area.key, '') AS area_key,
    listing.details_enriched
FROM listings AS listing
LEFT JOIN areas AS area
  ON area.id = listing.area_id
WHERE listing.source = $1
  AND listing.external_id = ANY($2::text[])
`

type ListStoredListingsForEnrichmentParams struct {
	Source      string   `json:"source"`
	ExternalIds []string `json:"external_ids"`
}

type ListStoredListingsForEnrichmentRow struct {
	ExternalID      string   `json:"external_id"`
	PriceEUR        *int     `json:"price_eur"`
	Description     string   `json:"description"`
	Address         string   `json:"address"`
	Rooms           *int     `json:"rooms"`
	AreaM2          *float64 `json:"area_m2"`
	Floor           *int     `json:"floor"`
	TotalFloors     *int     `json:"total_floors"`
	BuildingSeries  string   `json:"building_series"`
	BuildingType    string   `json:"building_type"`
	LandAreaM2      *float64 `json:"land_area_m2"`
	ImageURL        string   `json:"image_url"`
	PhotoURLs       []byte   `json:"photo_urls"`
	AreaKey         string   `json:"area_key"`
	DetailsEnriched bool     `json:"details_enriched"`
}

func (q *Queries) ListStoredListingsForEnrichment(ctx context.Context, arg ListStoredListingsForEnrichmentParams) ([]ListStoredListingsForEnrichmentRow, error) {
	rows, err := q.db.Query(ctx, listStoredListingsForEnrichment, arg.Source, arg.ExternalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoredListingsForEnrichmentRow{}
	for rows.Next() {
		var i ListStoredListingsForEnrichmentRow
		if err := rows.Scan(
			&i.ExternalID,
			&i.PriceEUR,
			&i.Description,
			&i.Address,
			&i.Rooms,
			&i.AreaM2,
			&i.Floor,
			&i.TotalFloors,
			&i.BuildingSeries,
			&i.BuildingType,
			&i.LandAreaM2,
			&i.ImageURL,
			&i.PhotoURLs,
			&i.AreaKey,
			&i.DetailsEnriched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadListing = `-- name: LoadListing :one
SELECT
    listing.id,
    listing.source,
    listing.external_id,
    listing.url,
    listing.property_type,
    listing.deal_type,
    listing.title,
    listing.description,
    listing.normalized_address,
    listing.normalized_description,
    listing.price_eur,
    listing.rooms,
    listing.area_m2,
    coalesce(listing.city, '') AS city,
    coalesce(listing.district, '') AS district,
    coalesce(listing.address, '') AS address,
    listing.floor,
    listing.total_floors,
    coalesce(listing.building_series, '') AS building_series,
    coalesce(listing.building_type, '') AS building_type,
    listing.land_area_m2,
    listing.details_enriched,
    listing.published_at,
    coalesce(listing.image_url, '') AS image_url,
    listing.photo_urls,
    coalesce(area.key, '') AS area_key,
    coalesce(area.name, '') AS area_name,
    coalesce(area.type, '') AS area_type,
    coalesce(parent_area.key, '') AS area_parent_key,
    coalesce(parent_area.name, '') AS area_parent_name,
    coalesce(source_area.external_key, '') AS source_area_key,
    coalesce(source_area.raw_name, '') AS source_area_name,
    listing.availability_status,
    listing.first_seen_at,
    listing.last_seen_at,
    listing.availability_changed_at
FROM listings AS listing
LEFT JOIN areas AS area
  ON area.id = listing.area_id
LEFT JOIN areas AS parent_area
  ON parent_area.id = area.parent_id
LEFT JOIN source_areas AS source_area
  ON source_area.id = listing.source_area_id
WHERE listing.id = $1
`

type LoadListingRow struct {
	ID                    int64              `json:"id"`
	Source                string             `json:"source"`
	ExternalID            string             `json:"external_id"`
	URL                   string             `json:"url"`
	PropertyType          string             `json:"property_type"`
	DealType              string             `json:"deal_type"`
	Title                 string             `json:"title"`
	Description           string             `json:"description"`
	NormalizedAddress     string             `json:"normalized_address"`
	NormalizedDescription string             `json:"normalized_description"`
	PriceEUR              *int               `json:"price_eur"`
	Rooms                 *int               `json:"rooms"`
	AreaM2                *float64           `json:"area_m2"`
	City                  string             `json:"city"`
	District              string             `json:"district"`
	Address               string             `json:"address"`
	Floor                 *int               `json:"floor"`
	TotalFloors           *int               `json:"total_floors"`
	BuildingSeries        string             `json:"building_series"`
	BuildingType          string             `json:"building_type"`
	LandAreaM2            *float64           `json:"land_area_m2"`
	DetailsEnriched       bool               `json:"details_enriched"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	ImageURL              string             `json:"image_url"`
	PhotoURLs             []byte             `json:"photo_urls"`
	AreaKey               string             `json:"area_key"`
	AreaName              string             `json:"area_name"`
	AreaType              string             `json:"area_type"`
	AreaParentKey         string             `json:"area_parent_key"`
	AreaParentName        string             `json:"area_parent_name"`
	SourceAreaKey         string             `json:"source_area_key"`
	SourceAreaName        string             `json:"source_area_name"`
	AvailabilityStatus    string             `json:"availability_status"`
	FirstSeenAt           pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt            pgtype.Timestamptz `json:"last_seen_at"`
	AvailabilityChangedAt pgtype.Timestamptz `json:"availability_changed_at"`
}

func (q *Queries) LoadListing(ctx context.Context, listingID int64) (LoadListingRow, error) {
	row := q.db.QueryRow(ctx, loadListing, listingID)
	var i LoadListingRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.PropertyType,
		&i.DealType,
		&i.Title,
		&i.Description,
		&i.NormalizedAddress,
		&i.NormalizedDescription,
		&i.PriceEUR,
		&i.Rooms,
		&i.AreaM2,
		&i.City,
		&i.District,
		&i.Address,
		&i.Floor,
		&i.TotalFloors,
		&i.BuildingSeries,
		&i.BuildingType,
		&i.LandAreaM2,
		&i.DetailsEnriched,
		&i.PublishedAt,
		&i.ImageURL,
		&i.PhotoURLs,
		&i.AreaKey,
		&i.AreaName,
		&i.AreaType,
		&i.AreaParentKey,
		&i.AreaParentName,
		&i.SourceAreaKey,
		&i.SourceAreaName,
		&i.AvailabilityStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.AvailabilityChangedAt,
	)
	return i, err
}

const updateExistingListing = `-- name: UpdateExistingListing :exec
UPDATE listings
SET url = $1,
    title = coalesce(nullif($2::text, ''), title),
    description = coalesce(nullif($3::text, ''), description),
    published_at = coalesce($4, published_at),
    image_url = coalesce(nullif($5::text, ''), image_url),
    area_id = coalesce($6, area_id),
    source_area_id = coalesce($7, source_area_id),
    price_eur = $8,
    rooms = coalesce($9, rooms),
    area_m2 = coalesce($10, area_m2),
    city = coalesce(nullif($11::text, ''), city),
    district = coalesce(nullif($12::text, ''), district),
    address = coalesce(nullif($13::text, ''), address),
    floor = coalesce($14, floor),
    total_floors = coalesce($15, total_floors),
    building_series = coalesce(nullif($16::text, ''), building_series),
    building_type = coalesce(nullif($17::text, ''), building_type),
    land_area_m2 = coalesce($18, land_area_m2),
    photo_urls = CASE
        WHEN jsonb_array_length($19::jsonb) > 0
            THEN $19::jsonb
        ELSE photo_urls
    END,
    details_enriched = details_enriched OR $20,
    raw_json = $21,
    availability_status = 'active',
    last_seen_at = $22,
    availability_changed_at = CASE
        WHEN availability_status <> 'active' THEN $22
        ELSE availability_changed_at
    END
WHERE id = $23
`

type UpdateExistingListingParams struct {
	URL             string             `json:"url"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ImageURL        string             `json:"image_url"`
	AreaID          *int64             `json:"area_id"`
	SourceAreaID    *int64             `json:"source_area_id"`
	PriceEUR        *int               `json:"price_eur"`
	Rooms           *int               `json:"rooms"`
	AreaM2          *float64           `json:"area_m2"`
	City            string             `json:"city"`
	District        string             `json:"district"`
	Address         string             `json:"address"`
	Floor           *int               `json:"floor"`
	TotalFloors     *int               `json:"total_floors"`
	BuildingSeries  string             `json:"building_series"`
	BuildingType    string             `json:"building_type"`
	LandAreaM2      *float64           `json:"land_area_m2"`
	PhotoURLs       []byte             `json:"photo_urls"`
	DetailsEnriched bool               `json:"details_enriched"`
	RawJSON         []byte             `json:"raw_json"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	ListingID       int64              `json:"listing_id"`
}

func (q *Queries) UpdateExistingListing(ctx context.Context, arg UpdateExistingListingParams) error {
	_, err := q.db.Exec(ctx, updateExistingListing,
		arg.URL,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.ImageURL,
		arg.AreaID,
		arg.SourceAreaID,
		arg.PriceEUR,
		arg.Rooms,
		arg.AreaM2,
		arg.City,
		arg.District,
		arg.Address,
		arg.Floor,
		arg.TotalFloors,
		arg.BuildingSeries,
		arg.BuildingType,
		arg.LandAreaM2,
		arg.PhotoURLs,
		arg.DetailsEnriched,
		arg.RawJSON,
		arg.ObservedAt,
		arg.ListingID,
	)
	return err
}

const updateListingSignals = `-- name: UpdateListingSignals :exec
UPDATE listings
SET description = $1,
    normalized_address = $2,
    normalized_description = $3,
    address = coalesce(nullif($4::text, ''), address),
    rooms = coalesce($5, rooms),
    area_m2 = coalesce($6, area_m2),
    floor = coalesce($7, floor),
    total_floors = coalesce($8, total_floors),
    building_series = coalesce(nullif($9::text, ''), building_series),
    building_type = coalesce(nullif($10::text, ''), building_type),
    land_area_m2 = coalesce($11, land_area_m2),
    image_url = coalesce(nullif($12::text, ''), image_url),
    photo_urls = CASE
        WHEN jsonb_array_length($13::jsonb) > 0
            THEN $13::jsonb
        ELSE photo_urls
    END,
    details_enriched = details_enriched OR $14
WHERE id = $15
`

type UpdateListingSignalsParams struct {
	Description           string   `json:"description"`
	NormalizedAddress     string   `json:"normalized_address"`
	NormalizedDescription string   `json:"normalized_description"`
	Address               string   `json:"address"`
	Rooms                 *int     `json:"rooms"`
	AreaM2                *float64 `json:"area_m2"`
	Floor                 *int     `json:"floor"`
	TotalFloors           *int     `json:"total_floors"`
	BuildingSeries        string   `json:"building_series"`
	BuildingType          string   `json:"building_type"`
	LandAreaM2            *float64 `json:"land_area_m2"`
	ImageURL              string   `json:"image_url"`
	PhotoURLs             []byte   `json:"photo_urls"`
	DetailsEnriched       bool     `json:"details_enriched"`
	ListingID             int64    `json:"listing_id"`
}

func (q *Queries) UpdateListingSignals(ctx context.Context, arg UpdateListingSignalsParams) error {
	_, err := q.db.Exec(ctx, updateListingSignals,
		arg.Description,
		arg.NormalizedAddress,
		arg.NormalizedDescription,
		arg.Address,
		arg.Rooms,
		arg.AreaM2,
		arg.Floor,
		arg.TotalFloors,
		arg.BuildingSeries,
		arg.BuildingType,
		arg.LandAreaM2,
		arg.ImageURL,
		arg.PhotoURLs,
		arg.DetailsEnriched,
		arg.ListingID,
	)
	return err
}
