// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Area struct {
	ID       int64  `json:"id"`
	Key      string `json:"key"`
	ParentID *int64 `json:"parent_id"`
	Type     string `json:"type"`
	Name     string `json:"name"`
}

type ConsumedEvent struct {
	ConsumerName string             `json:"consumer_name"`
	EventID      pgtype.UUID        `json:"event_id"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
}

type CurrentActiveListingOffer struct {
	ID                    int64              `json:"id"`
	Source                string             `json:"source"`
	ExternalID            string             `json:"external_id"`
	URL                   string             `json:"url"`
	PropertyType          string             `json:"property_type"`
	DealType              string             `json:"deal_type"`
	PriceEUR              *int               `json:"price_eur"`
	Rooms                 *int               `json:"rooms"`
	AreaM2                *float64           `json:"area_m2"`
	City                  *string            `json:"city"`
	District              *string            `json:"district"`
	Address               *string            `json:"address"`
	Floor                 *int               `json:"floor"`
	TotalFloors           *int               `json:"total_floors"`
	BuildingSeries        *string            `json:"building_series"`
	BuildingType          *string            `json:"building_type"`
	LandAreaM2            *float64           `json:"land_area_m2"`
	DetailsEnriched       bool               `json:"details_enriched"`
	Title                 string             `json:"title"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	ImageURL              *string            `json:"image_url"`
	PhotoURLs             []byte             `json:"photo_urls"`
	AreaID                *int64             `json:"area_id"`
	SourceAreaID          *int64             `json:"source_area_id"`
	FirstSeenAt           pgtype.Timestamptz `json:"first_seen_at"`
	RawJSON               []byte             `json:"raw_json"`
	Description           string             `json:"description"`
	NormalizedAddress     string             `json:"normalized_address"`
	NormalizedDescription string             `json:"normalized_description"`
	AvailabilityStatus    string             `json:"availability_status"`
	LastSeenAt            pgtype.Timestamptz `json:"last_seen_at"`
	AvailabilityChangedAt pgtype.Timestamptz `json:"availability_changed_at"`
}

type DuplicateDecision struct {
	ID              int64              `json:"id"`
	LeftListingID   int64              `json:"left_listing_id"`
	RightListingID  int64              `json:"right_listing_id"`
	LeftSnapshotID  int64              `json:"left_snapshot_id"`
	RightSnapshotID int64              `json:"right_snapshot_id"`
	RuleVersion     string             `json:"rule_version"`
	Confidence      float64            `json:"confidence"`
	AutomaticStatus string             `json:"automatic_status"`
	Status          string             `json:"status"`
	Evidence        []byte             `json:"evidence"`
	EvaluatedAt     pgtype.Timestamptz `json:"evaluated_at"`
	OverriddenAt    pgtype.Timestamptz `json:"overridden_at"`
	OverrideReason  *string            `json:"override_reason"`
}

type DuplicateDecisionInspection struct {
	ID              int64              `json:"id"`
	RuleVersion     string             `json:"rule_version"`
	Confidence      float64            `json:"confidence"`
	AutomaticStatus string             `json:"automatic_status"`
	Status          string             `json:"status"`
	Evidence        []byte             `json:"evidence"`
	EvaluatedAt     pgtype.Timestamptz `json:"evaluated_at"`
	OverriddenAt    pgtype.Timestamptz `json:"overridden_at"`
	OverrideReason  *string            `json:"override_reason"`
	LeftSource      string             `json:"left_source"`
	LeftExternalID  string             `json:"left_external_id"`
	RightSource     string             `json:"right_source"`
	RightExternalID string             `json:"right_external_id"`
	LeftPropertyID  *int64             `json:"left_property_id"`
	RightPropertyID *int64             `json:"right_property_id"`
}

type DuplicateResolutionAttempt struct {
	ID             int64              `json:"id"`
	SnapshotID     int64              `json:"snapshot_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Outcome        string             `json:"outcome"`
	CandidateCount *int               `json:"candidate_count"`
	AcceptedCount  *int               `json:"accepted_count"`
	Error          *string            `json:"error"`
}

type DuplicateResolutionJob struct {
	SnapshotID    int64              `json:"snapshot_id"`
	Status        string             `json:"status"`
	Attempts      int                `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	LastError     *string            `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DuplicateScoreDistribution struct {
	RuleVersion   string      `json:"rule_version"`
	Status        string      `json:"status"`
	ScoreBucket   interface{} `json:"score_bucket"`
	DecisionCount int64       `json:"decision_count"`
}

type Filter struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	Enabled       bool               `json:"enabled"`
	DealType      string             `json:"deal_type"`
	PropertyTypes []string           `json:"property_types"`
	PriceMin      *int               `json:"price_min"`
	PriceMax      *int               `json:"price_max"`
	RoomsMin      *int               `json:"rooms_min"`
	RoomsMax      *int               `json:"rooms_max"`
	AreaMin       *float64           `json:"area_min"`
	AreaMax       *float64           `json:"area_max"`
	ActivatedAt   pgtype.Timestamptz `json:"activated_at"`
}

type FilterArea struct {
	FilterID int64 `json:"filter_id"`
	AreaID   int64 `json:"area_id"`
}

type Listing struct {
	ID                    int64              `json:"id"`
	Source                string             `json:"source"`
	ExternalID            string             `json:"external_id"`
	URL                   string             `json:"url"`
	PropertyType          string             `json:"property_type"`
	DealType              string             `json:"deal_type"`
	PriceEUR              *int               `json:"price_eur"`
	Rooms                 *int               `json:"rooms"`
	AreaM2                *float64           `json:"area_m2"`
	City                  *string            `json:"city"`
	District              *string            `json:"district"`
	Address               *string            `json:"address"`
	Floor                 *int               `json:"floor"`
	TotalFloors           *int               `json:"total_floors"`
	BuildingSeries        *string            `json:"building_series"`
	BuildingType          *string            `json:"building_type"`
	LandAreaM2            *float64           `json:"land_area_m2"`
	DetailsEnriched       bool               `json:"details_enriched"`
	Title                 string             `json:"title"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	ImageURL              *string            `json:"image_url"`
	PhotoURLs             []byte             `json:"photo_urls"`
	AreaID                *int64             `json:"area_id"`
	SourceAreaID          *int64             `json:"source_area_id"`
	FirstSeenAt           pgtype.Timestamptz `json:"first_seen_at"`
	RawJSON               []byte             `json:"raw_json"`
	Description           string             `json:"description"`
	NormalizedAddress     string             `json:"normalized_address"`
	NormalizedDescription string             `json:"normalized_description"`
	AvailabilityStatus    string             `json:"availability_status"`
	LastSeenAt            pgtype.Timestamptz `json:"last_seen_at"`
	AvailabilityChangedAt pgtype.Timestamptz `json:"availability_changed_at"`
}

type ListingAvailabilityAttempt struct {
	ID         int64              `json:"id"`
	ListingID  int64              `json:"listing_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Outcome    string             `json:"outcome"`
	Evidence   *string            `json:"evidence"`
	Error      *string            `json:"error"`
}

type ListingAvailabilityJob struct {
	ListingID         int64              `json:"listing_id"`
	Status            string             `json:"status"`
	Attempts          int                `json:"attempts"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	ClaimedAt         pgtype.Timestamptz `json:"claimed_at"`
	LastError         *string            `json:"last_error"`
	PriorityRequested bool               `json:"priority_requested"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ListingAvailabilityObservation struct {
	ID              int64              `json:"id"`
	ListingID       int64              `json:"listing_id"`
	Status          string             `json:"status"`
	PreviousStatus  *string            `json:"previous_status"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	ObservationKind string             `json:"observation_kind"`
	Evidence        string             `json:"evidence"`
	IsTransition    bool               `json:"is_transition"`
}

type ListingPhoto struct {
	ListingID      int64  `json:"listing_id"`
	Position       int16  `json:"position"`
	TelegramFileID string `json:"telegram_file_id"`
}

type ListingPhotoFingerprint struct {
	ID                  int64              `json:"id"`
	SnapshotID          int64              `json:"snapshot_id"`
	ListingID           int64              `json:"listing_id"`
	Position            int16              `json:"position"`
	SourceURL           string             `json:"source_url"`
	ExactHash           string             `json:"exact_hash"`
	ExactAlgorithm      string             `json:"exact_algorithm"`
	PerceptualHash      string             `json:"perceptual_hash"`
	PerceptualAlgorithm string             `json:"perceptual_algorithm"`
	MediaType           string             `json:"media_type"`
	ByteSize            int                `json:"byte_size"`
	Width               int                `json:"width"`
	Height              int                `json:"height"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ListingPriceHistory struct {
	ID         int64              `json:"id"`
	ListingID  int64              `json:"listing_id"`
	PriceEUR   *int               `json:"price_eur"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

type ListingSignalAttempt struct {
	ID         int64              `json:"id"`
	ListingID  int64              `json:"listing_id"`
	Generation int64              `json:"generation"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Outcome    string             `json:"outcome"`
	Error      *string            `json:"error"`
}

type ListingSignalJob struct {
	ListingID     int64              `json:"listing_id"`
	Generation    int64              `json:"generation"`
	Status        string             `json:"status"`
	Attempts      int                `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	LastError     *string            `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ListingSignalSnapshot struct {
	ID                    int64              `json:"id"`
	ListingID             int64              `json:"listing_id"`
	InputHash             string             `json:"input_hash"`
	NormalizationVersion  string             `json:"normalization_version"`
	Description           string             `json:"description"`
	NormalizedAddress     string             `json:"normalized_address"`
	NormalizedDescription string             `json:"normalized_description"`
	StructuredFacts       []byte             `json:"structured_facts"`
	PhotoURLs             []byte             `json:"photo_urls"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
}

type Notification struct {
	ID                  int64              `json:"id"`
	FilterID            int64              `json:"filter_id"`
	ListingID           int64              `json:"listing_id"`
	Status              string             `json:"status"`
	Attempts            int                `json:"attempts"`
	NextAttemptAt       pgtype.Timestamptz `json:"next_attempt_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	LastError           *string            `json:"last_error"`
	TriggerEventID      pgtype.UUID        `json:"trigger_event_id"`
	NotificationType    string             `json:"notification_type"`
	PreviousPriceEUR    *int               `json:"previous_price_eur"`
	CurrentPriceEUR     *int               `json:"current_price_eur"`
	PropertyID          *int64             `json:"property_id"`
	ComparisonListingID *int64             `json:"comparison_listing_id"`
	ListingSnapshot     []byte             `json:"listing_snapshot"`
	ActiveAlternatives  []byte             `json:"active_alternatives"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	EventType     string             `json:"event_type"`
	AggregateID   int64              `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Attempts      int                `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     *string            `json:"last_error"`
}

type Property struct {
	ID                   int64              `json:"id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	MergedIntoPropertyID *int64             `json:"merged_into_property_id"`
	MergedAt             pgtype.Timestamptz `json:"merged_at"`
}

type PropertyListingMembership struct {
	ID         int64              `json:"id"`
	PropertyID int64              `json:"property_id"`
	ListingID  int64              `json:"listing_id"`
	DecisionID *int64             `json:"decision_id"`
	ValidFrom  pgtype.Timestamptz `json:"valid_from"`
	ValidTo    pgtype.Timestamptz `json:"valid_to"`
	Reason     string             `json:"reason"`
}

type SourceArea struct {
	ID          int64   `json:"id"`
	Source      string  `json:"source"`
	ExternalKey string  `json:"external_key"`
	RawName     *string `json:"raw_name"`
	AreaID      *int64  `json:"area_id"`
}

type SourceState struct {
	SourceKey     string             `json:"source_key"`
	Initialized   bool               `json:"initialized"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
}

type User struct {
	ID             int64              `json:"id"`
	TelegramUserID int64              `json:"telegram_user_id"`
	ChatID         int64              `json:"chat_id"`
	Name           *string            `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LanguageTag    string             `json:"language_tag"`
}
