// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDuplicateAwareNotification = `-- name: InsertDuplicateAwareNotification :execrows
INSERT INTO notifications (
    filter_id,
    listing_id,
    trigger_event_id,
    notification_type,
    previous_price_eur,
    current_price_eur,
    property_id,
    comparison_listing_id,
    listing_snapshot,
    active_alternatives,
    status,
    next_attempt_at
) VALUES (
    $1,
    $2,
    $3::text::uuid,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    'pending',
    now()
)
ON CONFLICT DO NOTHING
`

type InsertDuplicateAwareNotificationParams struct {
	FilterID            int64  `json:"filter_id"`
	ListingID           int64  `json:"listing_id"`
	EventID             string `json:"event_id"`
	NotificationType    string `json:"notification_type"`
	PreviousPriceEUR    *int   `json:"previous_price_eur"`
	CurrentPriceEUR     *int   `json:"current_price_eur"`
	PropertyID          *int64 `json:"property_id"`
	ComparisonListingID *int64 `json:"comparison_listing_id"`
	ListingSnapshot     []byte `json:"listing_snapshot"`
	ActiveAlternatives  []byte `json:"active_alternatives"`
}

func (q *Queries) InsertDuplicateAwareNotification(ctx context.Context, arg InsertDuplicateAwareNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDuplicateAwareNotification,
		arg.FilterID,
		arg.ListingID,
		arg.EventID,
		arg.NotificationType,
		arg.PreviousPriceEUR,
		arg.CurrentPriceEUR,
		arg.PropertyID,
		arg.ComparisonListingID,
		arg.ListingSnapshot,
		arg.ActiveAlternatives,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMatchedNotification = `-- name: InsertMatchedNotification :execrows
INSERT INTO notifications (
    filter_id,
    listing_id,
    trigger_event_id,
    notification_type,
    previous_price_eur,
    current_price_eur,
    listing_snapshot,
    status,
    next_attempt_at
) VALUES (
    $1,
    $2,
    $3::text::uuid,
    $4,
    $5,
    $6,
    $7,
    'pending',
    now()
)
ON CONFLICT (filter_id, trigger_event_id) DO NOTHING
`

type InsertMatchedNotificationParams struct {
	FilterID         int64  `json:"filter_id"`
	ListingID        int64  `json:"listing_id"`
	EventID          string `json:"event_id"`
	NotificationType string `json:"notification_type"`
	PreviousPriceEUR *int   `json:"previous_price_eur"`
	CurrentPriceEUR  *int   `json:"current_price_eur"`
	ListingSnapshot  []byte `json:"listing_snapshot"`
}

func (q *Queries) InsertMatchedNotification(ctx context.Context, arg InsertMatchedNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMatchedNotification,
		arg.FilterID,
		arg.ListingID,
		arg.EventID,
		arg.NotificationType,
		arg.PreviousPriceEUR,
		arg.CurrentPriceEUR,
		arg.ListingSnapshot,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPendingNotifications = `-- name: ListPendingNotifications :many
SELECT
    notification.id AS notification_id,
    notification.filter_id,
    notification.attempts,
    notification.notification_type,
    notification.previous_price_eur,
    notification.current_price_eur,
    notification.property_id,
    notification.comparison_listing_id,
    notification.listing_snapshot,
    notification.active_alternatives,
    app_user.telegram_user_id,
    coalesce(app_user.name, '') AS user_name,
    app_user.chat_id,
    app_user.language_tag,
    listing.id AS listing_id,
    listing.source,
    listing.external_id,
    listing.url,
    listing.property_type,
    listing.deal_type,
    listing.title,
    listing.price_eur,
    listing.rooms,
    listing.area_m2,
    coalesce(listing.city, '') AS city,
    coalesce(listing.district, '') AS district,
    coalesce(listing.address, '') AS address,
    listing.floor,
    listing.total_floors,
    coalesce(listing.building_series, '') AS building_series,
    coalesce(listing.building_type, '') AS building_type,
    listing.land_area_m2,
    listing.details_enriched,
    listing.published_at,
    coalesce(listing.image_url, '') AS image_url,
    listing.photo_urls,
    coalesce(area.key, '') AS area_key,
    coalesce(area.name, '') AS area_name,
    coalesce(area.type, '') AS area_type,
    coalesce(parent_area.key, '') AS area_parent_key,
    coalesce(parent_area.name, '') AS area_parent_name,
    coalesce(source_area.external_key, '') AS source_area_key,
    coalesce(source_area.raw_name, '') AS source_area_name
FROM notifications AS notification
JOIN filters AS filter
  ON filter.id = notification.filter_id
JOIN users AS app_user
  ON app_user.id = filter.user_id
JOIN listings AS listing
  ON listing.id = notification.listing_id
LEFT JOIN areas AS area
  ON area.id = listing.area_id
LEFT JOIN areas AS parent_area
  ON parent_area.id = area.parent_id
LEFT JOIN source_areas AS source_area
  ON source_area.id = listing.source_area_id
WHERE notification.status = 'pending'
  AND notification.next_attempt_at <= now()
  AND filter.enabled = TRUE
ORDER BY notification.next_attempt_at, notification.id
LIMIT $1
`

type ListPendingNotificationsRow struct {
	NotificationID      int64              `json:"notification_id"`
	FilterID            int64              `json:"filter_id"`
	Attempts            int                `json:"attempts"`
	NotificationType    string             `json:"notification_type"`
	PreviousPriceEUR    *int               `json:"previous_price_eur"`
	CurrentPriceEUR     *int               `json:"current_price_eur"`
	PropertyID          *int64             `json:"property_id"`
	ComparisonListingID *int64             `json:"comparison_listing_id"`
	ListingSnapshot     []byte             `json:"listing_snapshot"`
	ActiveAlternatives  []byte             `json:"active_alternatives"`
	TelegramUserID      int64              `json:"telegram_user_id"`
	UserName            string             `json:"user_name"`
	ChatID              int64              `json:"chat_id"`
	LanguageTag         string             `json:"language_tag"`
	ListingID           int64              `json:"listing_id"`
	Source              string             `json:"source"`
	ExternalID          string             `json:"external_id"`
	URL                 string             `json:"url"`
	PropertyType        string             `json:"property_type"`
	DealType            string             `json:"deal_type"`
	Title               string             `json:"title"`
	PriceEUR            *int               `json:"price_eur"`
	Rooms               *int               `json:"rooms"`
	AreaM2              *float64           `json:"area_m2"`
	City                string             `json:"city"`
	District            string             `json:"district"`
	Address             string             `json:"address"`
	Floor               *int               `json:"floor"`
	TotalFloors         *int               `json:"total_floors"`
	BuildingSeries      string             `json:"building_series"`
	BuildingType        string             `json:"building_type"`
	LandAreaM2          *float64           `json:"land_area_m2"`
	DetailsEnriched     bool               `json:"details_enriched"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	ImageURL            string             `json:"image_url"`
	PhotoURLs           []byte             `json:"photo_urls"`
	AreaKey             string             `json:"area_key"`
	AreaName            string             `json:"area_name"`
	AreaType            string             `json:"area_type"`
	AreaParentKey       string             `json:"area_parent_key"`
	AreaParentName      string             `json:"area_parent_name"`
	SourceAreaKey       string             `json:"source_area_key"`
	SourceAreaName      string             `json:"source_area_name"`
}

func (q *Queries) ListPendingNotifications(ctx context.Context, notificationLimit int32) ([]ListPendingNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingNotifications, notificationLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingNotificationsRow{}
	for rows.Next() {
		var i ListPendingNotificationsRow
		if err := rows.Scan(
			&i.NotificationID,
			&i.FilterID,
			&i.Attempts,
			&i.NotificationType,
			&i.PreviousPriceEUR,
			&i.CurrentPriceEUR,
			&i.PropertyID,
			&i.ComparisonListingID,
			&i.ListingSnapshot,
			&i.ActiveAlternatives,
			&i.TelegramUserID,
			&i.UserName,
			&i.ChatID,
			&i.LanguageTag,
			&i.ListingID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.PropertyType,
			&i.DealType,
			&i.Title,
			&i.PriceEUR,
			&i.Rooms,
			&i.AreaM2,
			&i.City,
			&i.District,
			&i.Address,
			&i.Floor,
			&i.TotalFloors,
			&i.BuildingSeries,
			&i.BuildingType,
			&i.LandAreaM2,
			&i.DetailsEnriched,
			&i.PublishedAt,
			&i.ImageURL,
			&i.PhotoURLs,
			&i.AreaKey,
			&i.AreaName,
			&i.AreaType,
			&i.AreaParentKey,
			&i.AreaParentName,
			&i.SourceAreaKey,
			&i.SourceAreaName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
