// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signals.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertListingSignalSnapshot = `-- name: InsertListingSignalSnapshot :one
INSERT INTO listing_signal_snapshots (
    listing_id,
    input_hash,
    normalization_version,
    description,
    normalized_address,
    normalized_description,
    structured_facts,
    photo_urls,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (listing_id, input_hash, normalization_version) DO NOTHING
RETURNING id
`

type InsertListingSignalSnapshotParams struct {
	ListingID             int64              `json:"listing_id"`
	InputHash             string             `json:"input_hash"`
	NormalizationVersion  string             `json:"normalization_version"`
	Description           string             `json:"description"`
	NormalizedAddress     string             `json:"normalized_address"`
	NormalizedDescription string             `json:"normalized_description"`
	StructuredFacts       []byte             `json:"structured_facts"`
	PhotoURLs             []byte             `json:"photo_urls"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) InsertListingSignalSnapshot(ctx context.Context, arg InsertListingSignalSnapshotParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertListingSignalSnapshot,
		arg.ListingID,
		arg.InputHash,
		arg.NormalizationVersion,
		arg.Description,
		arg.NormalizedAddress,
		arg.NormalizedDescription,
		arg.StructuredFacts,
		arg.PhotoURLs,
		arg.CompletedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPhotoFingerprint = `-- name: InsertPhotoFingerprint :exec
INSERT INTO listing_photo_fingerprints (
    snapshot_id,
    listing_id,
    position,
    source_url,
    exact_hash,
    exact_algorithm,
    perceptual_hash,
    perceptual_algorithm,
    media_type,
    byte_size,
    width,
    height,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
ON CONFLICT (snapshot_id, position) DO NOTHING
`

type InsertPhotoFingerprintParams struct {
	SnapshotID          int64              `json:"snapshot_id"`
	ListingID           int64              `json:"listing_id"`
	Position            int16              `json:"position"`
	SourceURL           string             `json:"source_url"`
	ExactHash           string             `json:"exact_hash"`
	ExactAlgorithm      string             `json:"exact_algorithm"`
	PerceptualHash      string             `json:"perceptual_hash"`
	PerceptualAlgorithm string             `json:"perceptual_algorithm"`
	MediaType           string             `json:"media_type"`
	ByteSize            int                `json:"byte_size"`
	Width               int                `json:"width"`
	Height              int                `json:"height"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertPhotoFingerprint(ctx context.Context, arg InsertPhotoFingerprintParams) error {
	_, err := q.db.Exec(ctx, insertPhotoFingerprint,
		arg.SnapshotID,
		arg.ListingID,
		arg.Position,
		arg.SourceURL,
		arg.ExactHash,
		arg.ExactAlgorithm,
		arg.PerceptualHash,
		arg.PerceptualAlgorithm,
		arg.MediaType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.CreatedAt,
	)
	return err
}

const listReusablePhotoFingerprints = `-- name: ListReusablePhotoFingerprints :many
SELECT DISTINCT ON (source_url)
    position,
    source_url,
    exact_hash,
    exact_algorithm,
    perceptual_hash,
    perceptual_algorithm,
    media_type,
    byte_size,
    width,
    height
FROM listing_photo_fingerprints
WHERE listing_id = $1
ORDER BY source_url, created_at DESC, id DESC
`

type ListReusablePhotoFingerprintsRow struct {
	Position            int16  `json:"position"`
	SourceURL           string `json:"source_url"`
	ExactHash           string `json:"exact_hash"`
	ExactAlgorithm      string `json:"exact_algorithm"`
	PerceptualHash      string `json:"perceptual_hash"`
	PerceptualAlgorithm string `json:"perceptual_algorithm"`
	MediaType           string `json:"media_type"`
	ByteSize            int    `json:"byte_size"`
	Width               int    `json:"width"`
	Height              int    `json:"height"`
}

func (q *Queries) ListReusablePhotoFingerprints(ctx context.Context, listingID int64) ([]ListReusablePhotoFingerprintsRow, error) {
	rows, err := q.db.Query(ctx, listReusablePhotoFingerprints, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReusablePhotoFingerprintsRow{}
	for rows.Next() {
		var i ListReusablePhotoFingerprintsRow
		if err := rows.Scan(
			&i.Position,
			&i.SourceURL,
			&i.ExactHash,
			&i.ExactAlgorithm,
			&i.PerceptualHash,
			&i.PerceptualAlgorithm,
			&i.MediaType,
			&i.ByteSize,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
